### ISSUE TITLE
AST generator in the roadmap?

### ISSUE THREAD

**Issue by dominickpastore** [mity/md4c#159]
I hope you don't mind me asking this in an issue. I'm not really sure where else to ask.

Are there any plans to add an AST generation module on top of the existing `md_parse` API? I saw at one point, you mentioned having done some some work on this [in an old discussion](https://talk.commonmark.org/t/why-is-md4c-so-fast-c/2520/14), but it seems like that did not go anywhere.

The reason I am asking: I am planning to add a module to [PyMD4C](https://github.com/dominickpastore/pymd4c) for AST generation. The original motivation was to make writing some test cases easier, but it seems like something certain applications might find useful (e.g. for syntax tree transformations) so I figured I'd make it a proper part of the library.

That said, if there were any sort of plans for MD4C to ever support AST generation, I don't want to release my own Python API now and it turn out to be incompatible.

**Comment by mity** [comment]
Indeed, I was working on it. But it was meant just as an experiment for making some performance comparisons with cmark rather than a serious attempt to add more functionality, and it turned out to be more work than I was willing to invest into it, so no, nothing in the roadmap unless somebody else comes and contributes it.

**Comment by dominickpastore** [comment]
That makes sense. Thanks!
