### ISSUE TITLE
Valgrind error: "Conditional jump or move depends on uninitialised value(s)"

### ISSUE THREAD

**Issue by chowette** [mity/md4c#176]
See this file

```
1. list item


problem with 2 line after a list
```
"Conditional jump or move depends on uninitialised value(s)" 
 This is related to the patch #6 and point to this line
https://github.com/mity/md4c/blob/e9ff661ff818ee94a4a231958d9b6768dc6882c9/src/md4c.c#L5897

**Comment by xdevelnet** [comment]
I just checked the code and didn't find anything suspicious.

What it does is makes a pointer at ctx->block_bytes but with shifted address (+ ctx->n_block_bytes - sizeof(MD_BLOCK) )

IMO the only reason of "Conditional jump or move depends on uninitialised value(s)" is because of some mistake on address shifting calculation. It may be beyond MD_BLOCK structure location.

@mity would you kindly comment on that?

**Comment by mity** [comment]
Unable to reproduce (tried release 0.4.8 and current head).
