### ISSUE TITLE
Tag `<gi att1=tok1 att2=tok2>` not recognized

### ISSUE THREAD

**Issue by tin-pot** [mity/md4c#2]
In `md_is_html_tag()`, state 41 "in middle of unquoted attribute value" is not exited when white space is encounterd. As a consequence, in the tag mentioned above the second `=` throws scanning off, we end up in the "unexpected" case, do `return FALSE` - and the tag is not recognized as such.

**Comment by tin-pot** [comment]
Here https://github.com/tin-pot/md4c/commit/e8c95ee4009e579455aeca7534c3ab4fa1d211cf is an obvious fix, but you might prefer using the `ISWHITESPACE()` macro.

Not sure about handling of new-line `\n` inside tags here and elsewhere ...

**Comment by mity** [comment]
Thanks for the report.

The fix is implemented a bit differently then your proposal, to handle the line breaks correctly:
 * For raw HTML blocks, the tag would have to be on a single line.
 * For inline raw HTML, it has to handle some (ignored) prefixes like '>' or indentation if nested e.g. in a block quote or list item.
